#!/usr/bin/env bash
set -e

print_summaries() {

  local fj_commands="$(fj commands)"
  local commands=()
  local summaries=()
  local longest_command=0
  local command

  if [[ "$0" == *help ]]; then
    fj_commands="$(fj commands $_SUB_COMMAND_VARS)"
    if [ -f "$fj_commands" ]; then
      print_help $fj_commands
      exit
    fi
  fi

  for command in ${fj_commands[@]}; do
    local file="$(command_path "$command")"
    if [ ! -h "$file" ] && [ -f "$file" ]; then
      local summary="$(summary "$file")"
      if [ -n "$summary" ]; then

        if [ -d "$_SUB_COMMAND_ROOT/fj-$command" ]; then
          commands["${#commands[@]}"]="-> $command"
        else
          commands["${#commands[@]}"]="$command"
        fi

        summaries["${#summaries[@]}"]="$summary"

        if [ "${#command}" -gt "$longest_command" ]; then
          longest_command=`expr ${#command} + 3`
        fi
      fi
    fi
  done

  local index
  local columns="$(tput cols)"
  local summary_length=$(( $columns - $longest_command - 5 ))

  for (( index=0; index < ${#commands[@]}; index++ )); do
    printf "   %-${longest_command}s  %s\n" "${commands[$index]}" \
      "$(truncate "$summary_length" "${summaries[$index]}")"
  done
}

print_help() {
  local file="$1"
  local usage="$(usage "$file")"

  if [ -n "$usage" ]; then
    echo "$usage"

    local help="$(help "$file")"
    [ -n "$help" ] && echo && echo "$help"
  else
    echo "Sorry, this command isn't documented yet."
  fi
}

command_path() {
  fj_path="$(command -v "fj-$command" || command -v "fj-sh-$command" || true)"
  if [ "$fj_path" == "" ] && [ -f "$_SUB_COMMAND_ROOT/fj-$command/fj-$command" ]; then
    echo "$_SUB_COMMAND_ROOT/fj-$command/fj-$command"
  else
    echo "$fj_path"
  fi
}

summary() {
  sed -n "s/^# Summary: \(.*\)/\1/p" "$1"
}

usage() {
  sed -n "s/^# \(Usage: .*\)/\1/p" "$1"
}

help() {
  awk '/^[^#]/{p=0} /^# Help:/{p=1} p' "$1" | sed "s/^# Help: //;s/^# //;s/^#//"
}

truncate() {
  local max_length="$1"
  local string="$2"

  if [ "${#string}" -gt "$max_length" ]; then
    local length=$(( $max_length - 3 ))
    echo "${string:0:$length}..."
  else
    echo "$string"
  fi
}

print_command_help() {
  local file="$1"
  local usage="$(usage "$file")"

  if [ -n "$usage" ]; then
    echo "$usage"

    local help="$(help "$file")"
    [ -n "$help" ] && echo && echo "$help"

    local _SUB_SUMMARY="$(print_summaries)"

    if [ ! "$_SUB_SUMMARY" == "" ]; then
      echo "
Some useful fj $command commands are:

$(print_summaries)

See 'fj $_SUB_COMMAND_VARS [command]' for information on a specific command."
    fi
  else
    echo "Sorry, this command isn't documented yet."
  fi
}

# Provide fj completions
if [ "$1" = "--complete" ]; then
  echo "$(fj commands)"
  exit
fi

command="$_SUB_COMMAND_FILE"
if [[ "$command" == "" || "$command" == "help" ]] && [[ ! "$_SUB_COMMAND_ROOT" == *fj-$_SUB_COMMAND_FILE ]]; then
echo "Usage: fj $command [<args>]

Some useful fj $command commands are:
$(print_summaries)

See 'fj $_SUB_COMMAND_VARS' for information on a specific command."

else
  file="$(command_path "$command")"

  if [ -n "$file" ]; then
    if [[ "$_SUB_COMMAND_ROOT" == *fj-$_SUB_COMMAND_FILE ]]; then
      print_command_help "$file"
    else
      print_help "$file"
    fi
  else
    echo "fj: no such command \`$command'" >&2
    exit 1
  fi
fi
